language: go

go:
    - 1.5
    - tip

install:
    # dep for rrframework
    - go get gopkg.in/redis.v5
    - go get github.com/golang/protobuf/proto
    - go get github.com/samuel/go-zookeeper/zk
    # dep for laosj
    - go get github.com/PuerkitoBio/goquery
    - go get github.com/songtianyi/rrframework

script:
    - go build mzitu.go
    - go build mzituzp.go
